# Generated by Django 2.2 on 2021-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='ok', max_length=240),
            preserve_default=False,
        ),
    ]
